name: GH assignees

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign PR'
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: hamid-Ft
          repo-token: ${{ secrets.GITHUB_TOKEN }}
