name: Greetings

on: 
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Greet new user
      uses: actions/github-script@v7
      with:
        script: |
          const issueComment = context.issue({ body: 'Thanks for opening this issue!' });
          const newIssue = await github.issues.createComment(issueComment);