name: 'Hello'

on:
  pull_request:
    types: [opened, reopened]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/action
        with:
          gh-token: ${{secrets.GITHUB_TOKEN}}
          label: 'enhancement'
